# -*- coding: utf-8 -*-
"""model_testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v_tLkWUWyOLGbBG-YEfkW5tk2irV4eLP
"""

import pickle
import numpy as np
loaded_model = pickle.load(open("/content/0.5814814567565918-acc-cnn-model.sav",'rb'))
arr1 = np.load("/content/back-1.csv_segment_5.npy",allow_pickle="True")
print(arr1,arr1.shape)

print(loaded_model.layers[0].input_shape)

original_tuple = arr1.shape
new_tuple = (None,) + original_tuple
print(new_tuple)

arr_reshaped = arr1.reshape(-1,256,4)

print(type(arr_reshaped))

pred = loaded_model.predict(arr_reshaped)
print(pred)